### ISSUE TITLE
Add JWT::verify() & support JWT::decode() without verify

### ISSUE THREAD

**Issue by duzun** [adhocore/php-jwt#12]
Sometimes it is useful to be able to decode the token without validation of the signature or timestamps.
And other times it is useful to just validate the token without (the need to) decoding it.

**Comment by adhocore** [comment]
thanks for trying it out and filing issue. :)

right but i can see more of misuse case than usecase.

ideally a jwt token that is not validated by signature verification is definitely malicious and spoofed one and server should not accept such token in anyway.

for your case, if you only want to read token but not really consume it i would suggest userland workaround:

**Comment by duzun** [comment]
Thanks for the clarification and for the lib :)

I see the point.
But what about `JWT::verify()` or `JWT::verifySignature()` which would not decode the payload?

**Comment by adhocore** [comment]
sorry, could you pls explain more?

**Comment by duzun** [comment]
I have such a use case:

The client authenticates with a JWT generated by the server.
I need to differentiate three cases:

1. JWT is valid and not expired,
2. JWT has a valid signature but it is expired,
3. JWT is invalid (attack?).

Case 1. and 3. are doable.

For case 2. it is safe to assume the client's identity is known, but not proven. The server would ask for prove of the identity (password), but not for the whole identity (username or email).

To be able to implement this, I would need to decode the payload of and expired JWT, without full validation, but also be able to verify the signature + integrity of the JWT.

I know how to do all this stuff, but I wanted it to be in one neat lib, and not have to write JWT related code in my app.

**Comment by adhocore** [comment]
> JWT has a valid signature but it is expired

again if it is expired then it should be rejected. a jwt token is most commonly used as bearer token which means whoever bears and uses that token can use it for good or bad. (you can use mine token if you discover it somehow). that's why bearer tokens are short lived 10-15 minutes.

if the jwt token is expired, your api client need to refresh it (get new) by using refresh_token.
it would be a hole to allow for expired tokens even if signature valid.

**Comment by duzun** [comment]
>> a jwt token is most commonly used as bearer token
But not always!
If expired, it should be rejected, true, but in my case it is not used as a bearer token when expired, not even for authorization, but only for identifying the user with no privileges whatsoever.

I understand why you don’t want to allow decoding of invalid tokens, but how would it compromise security if you allow to verify signature without decoding?

Thank you for you care of the security of my project and everyone’s using your lib.
But I know what I’m doing, I’m building a better UX without compromising security.

**Comment by adhocore** [comment]
if you really want to bypass timestamp validation (like expiry) you can spoof time like so
```php
$jwt = new Ahc\Jwt\JWT;

$jwt->setTestTimestamp(time() + 10000); // + or - as you need
```

as you can see it is named setTestTimestamp() as it is to be used for mocking a test scenarios (but not production)

for your usecase, this can be the most viable option without altering this library or having you to write boilerplates code. ;)

**Comment by duzun** [comment]
Thanks!

**Comment by moodstubos** [comment]
get payload of expired token would be very nice

example of nodes solution:

`const payload = jwt.verify(token, SECRET, {ignoreExpiration: true} );`

https://stackoverflow.com/questions/51281270/extract-payload-of-expired-jwt-token
