### ISSUE TITLE
validate with public key

### ISSUE THREAD

**Issue by boflor666** [adhocore/php-jwt#15]
Hi,

I managed to include this very user friendly library in a project and create a token that validates on jwt.io.
I am sending this token in a http header to another server where it needs to be validated. This is not working though. The other server only has access to the public key. When I try to `echo (new JWT($public_key))->decode($token); ` I receive an error:
> Uncaught Ahc\Jwt\JWTException: Invalid token: Signature failed in JWT.php:153 Stack trace: #0 ....Ahc\Jwt\JWT->decode(Array) #1 {main} thrown in JWT.php on line 153 

Surely I am doing something wrong. How can I validate the JWT string and decode it to retrieve its content?

**Comment by adhocore** [comment]
as explained in the doc, we only deal with private keys in this library. (public key where required is deduced dynamically)

the private key as the name suggests should be private, secret, unexposed and uncompromised in the **server** only. by server, i mean the web server that uses this library to emit jwt tokens. server uses this key to generate jwt token for clients. clients then make a claim (think of it as asking permission to access authenticated resource) to server using this jwt token. server validates this token by verifying it against the secret/hidden/private key which it only knows  but not outside world.

the client which makes request to the server using jwt as api token (via header or somehow) should not get to know the private key of the server.

**Comment by adhocore** [comment]
thank you for opening issue- your first ever in github it seems! 🎉

**Comment by boflor666** [comment]
hello, thank you for your answer. 
My usecase is like this: 

- my server 1 generates a JWT and posts it in a http header to webserver 2. 
- webserver 2 validates the JWT to check if the request did indeed come from server 1, if so stuff can happen.

How can server 2 validate the token generated by server 1? Is this not how JWT's are supposed to work?

**Comment by adhocore** [comment]
here server 1 is client
and server 2 is your data source

when server 1 hits token endpoint with correct credentials to server 2, server 2 generates jwt and gives back to server 1 as response

then server 1 continues to use jwt token received above to hit other protected endpoints of server 2. (server 2 can validate the token because it is the token it generated and it has secret keys to decode and verify the signature)

i suggest you take a look on API authentication with jwt

**Comment by adhocore** [comment]
closing. we can still continue discussion as required.
