### ISSUE TITLE
Unsupported algo PS256

### ISSUE THREAD

**Issue by hi2rashid** [adhocore/php-jwt#16]
An uncaught Exception was encountered

Type: Ahc\Jwt\JWTException

Message: Unsupported algo PS256

**Comment by adhocore** [comment]
did you mean to use `HS256`?

**Comment by hi2rashid** [comment]
PS256 - https://tools.ietf.org/html/rfc7518

**Comment by adhocore** [comment]
not yet supported by this library

**Comment by adhocore** [comment]
closing, no plans to support it anytime soon. might revisit later.
