### ISSUE TITLE
Pass key as string?

### ISSUE THREAD

**Issue by splitbrain** [adhocore/php-jwt#27]
From what I can see in docs, it seems only possible to pass a file path in the constructor. It would be helpful if I could pass the key directly as a string without having to create a file first (in my case it's coming from a database). Is there maybe a trick using the resource method somehow?

**Comment by adhocore** [comment]
i think you can directly set the resource as key.

```php
$key = openssl_pkey_get_private('your rsa key as string from database');
$jwt = new JWT($key, 'RS256');

// ...
```

**Comment by adhocore** [comment]
closing for now
