### ISSUE TITLE
Not working with PHP 7

### ISSUE THREAD

**Issue by thomaslanger** [adhocore/php-jwt#31]
Please change the description

**Comment by adhocore** [comment]
the tests are running from php7.1 to 8.2 and working fine
> https://github.com/adhocore/php-jwt/blob/main/.github/workflows/build.yml#L29-L35

it should still support php7.0 but i had to remove that due to compat issue with phpunit 
---

but anyway php7.0 is dead for long already and should not be used as well. im checking in on php7.0

**Comment by thomaslanger** [comment]
Ok, it works with PHP 7. Sorry, my fault ;-)
