### ISSUE TITLE
new JWT() - 500 Internal server error

### ISSUE THREAD

**Issue by MateusOFCZ** [adhocore/php-jwt#32]
Hello, when I call the route with `$jwt = new JWT('secret', 'HS256', 3600, 10);` on code, returns Server Error 500, I'm using Docker:

api/test.php:
```
<?php
  include "../vendor/autoload.php";
	use Ahc\Jwt\JWT;

  $jwt = new JWT('secret', 'HS256', 3600, 10);
?>
```

Error on POST:
![image](https://user-images.githubusercontent.com/41977530/198585791-7e045437-ae0f-4067-8d95-04d0a781d36f.png)

In Try Catch return this error:
```
Error Object
(
    [message:protected] => Class 'Ahc\Jwt\JWT' not found
    [string:Error:private] => 
    [code:protected] => 0
    [file:protected] => /var/www/html/api/test.php
    [line:protected] => 8
    [trace:Error:private] => Array
        (
        )

    [previous:Error:private] => 
)
```

When I remove `$jwt = new JWT('secret', 'HS256', 3600, 10);` the error not occurred.
Any idea how solve this?

**Comment by adhocore** [comment]
oh, it is autoload issue maybe? can you run `composer dump-autoload -o` once in the terminal from root dir?
