### ISSUE TITLE
problem with PEM file key

### ISSUE THREAD

**Issue by sbraaa** [adhocore/php-jwt#33]
I created a PEM file on server ubuntu 18 with openssl 1.1.1 using this code

```
 $privkey = openssl_pkey_new([
            'digest_alg' => 'sha256',
            'private_key_bits' => 1024,
            'private_key_type' => OPENSSL_KEYTYPE_RSA,
        ]);
        try {
            openssl_pkey_export_to_file($privkey, 'WEB-INF/config/' . $filename);
        } catch (Exception $e) {
            echo 'Caught exception: ',  $e->getMessage(), "\n";
        }
```

on the same server it runs well, encoding and decoding as expected.

Then if I try the to decode using the same PEM file on different server (wich use openssl 1.1.1f)  it doesn't run saying that signature is invalid.

Doing the same using a string instead of PEM file works. I cannot understand... could it be that PEM file I created depend on specficia server?

**Comment by adhocore** [comment]
it could be the openssl version too?

**Comment by adhocore** [comment]
cool, thanks for the update.
